### PR TITLE
Feat/offline prototypo

### PR DESCRIPTION
**Pull request by MartinBolot**
makes prototypo able to run offline thanks to "npm run offline" or "gulp offline" command

### CODE REVIEW

**Review by YoruNoHikage — APPROVED** [review]

**Review by Aldrian — APPROVED** [review]
👍

**Comment by YoruNoHikage** [comment]
This changed too much and should be either reworked differently or closed?

**Comment by Aldrian** [comment]
Definitely

**Comment by untoldbyte** [comment]
This works with what node version?

**Comment by untoldbyte** [comment]
local client is not defined errors in console, any ideas?

**Pull request closed without merging**
